export const SET_WIDTH = 'SET_WIDTH'
export const SET_HEIGHT = 'SET_HEIGHT'
export const SET_SYS_WIDTH = 'SET_SYS_WIDTH'
export const SET_SYS_HEIGHT = 'SET_SYS_HEIGHT'
export const SET_USERNAME = 'SET_USERNAME'
export const SET_ISLOGIN = 'SET_ISLOGIN'
export const SET_TOKENSTR = 'SET_TOKENSTR'
export const SET_PATH = 'SET_PATH'